project_id = "zglvtspmrihotbfbjtvw"

[functions.send-push]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.upload-character-images]
verify_jwt = false

[functions.auto-kick-blocked-members]
verify_jwt = false
